# -*- coding: utf-8 -*-
"""Project Presensi Ekstrakulikuler Pramuka SMKS Baitul Atieq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mIxOD2ZXk8GLnGlUR-f5LuuAfJ_hBHG4
"""

import pandas as pd

print("=== Sistem Presensi & Keaktifan — Ekstrakurikuler Pramuka SMKS BAITUL ATIEQ ===\n")

# Input Data Siswa

jumlah_siswa = int(input("Masukkan jumlah siswa: "))
nama_siswa = []

for i in range(jumlah_siswa):
    nama = input(f"Nama siswa ke-{i+1}: ")
    nama_siswa.append(nama)

# Buat DataFrame awal
df = pd.DataFrame({
    "Nama": nama_siswa,
    "Kehadiran (%)": 0,
    "Status Keaktifan": ""
})

# Input Presensi Mingguan

jumlah_pertemuan = int(input("\nMasukkan jumlah pertemuan yang ingin dicatat: "))

# Buat kolom pertemuan bertipe string
for pertemuan in range(1, jumlah_pertemuan + 1):
    df[f"Pertemuan_{pertemuan}"] = ""

print("\nMasukkan kehadiran siswa (1 = Hadir, 0 = Tidak Hadir)\n")

# Loop input presensi
for i in range(len(df)):
    total_hadir = 0
    for pertemuan in range(1, jumlah_pertemuan + 1):
        status_input = int(input(f"{df.loc[i, 'Nama']} - Pertemuan {pertemuan}: "))
        status = "Hadir" if status_input == 1 else "Tidak Hadir"
        df.loc[i, f"Pertemuan_{pertemuan}"] = status
        total_hadir += status_input

    # Hitung kehadiran & status keaktifan
    persen_hadir = (total_hadir / jumlah_pertemuan) * 100
    df.loc[i, "Kehadiran (%)"] = persen_hadir
    if persen_hadir >= 80:
        df.loc[i, "Status Keaktifan"] = "Aktif"
    elif persen_hadir >= 50:
        df.loc[i, "Status Keaktifan"] = "Cukup Aktif"
    else:
        df.loc[i, "Status Keaktifan"] = "Kurang Aktif"


# Rekapitulasi & Tampilkan Hasil

print("\n=== Rekapitulasi Presensi & Keaktifan ===")
display(df)


# Simpan ke File CSV

df.to_csv("rekap_presensi_pramuka.csv", index=False)
print("\nData presensi berhasil disimpan ke file: rekap_presensi_pramuka.csv ✅")

# Analisis Tambahan (Opsional - AI Simpel)

aktif = df[df["Status Keaktifan"] == "Aktif"]
kurang_aktif = df[df["Status Keaktifan"] == "Kurang Aktif"]

print("\n Analisis Singkat:")
print(f"- Total siswa: {len(df)}")
print(f"- Siswa aktif: {len(aktif)}")
print(f"- Siswa kurang aktif: {len(kurang_aktif)}")
print("\nRekomendasi AI Sederhana:")
if len(kurang_aktif) > 0:
    print(" Sarankan siswa kurang aktif untuk mengikuti kegiatan tambahan atau latihan disiplin.")
else:
    print(" Semua siswa aktif dan konsisten dalam kehadiran. Pertahankan semangatnya!")